### ISSUE TITLE
Releasing pipeline is failing

### ISSUE THREAD

**Issue by aeneasr** [ory/sdk#226]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

https://app.circleci.com/pipelines/github/ory/sdk/1223/workflows/63eddfc6-ac77-4411-80b0-cc980aed0c1a/jobs/1128

### Reproducing the bug

See above

### Version

master

### Additional Context

Maybe updating to openapi 6.2.1 solves the problem?

**Comment by jonas-jonas** [comment]
The issue is related to the python SDK generation seemingly being broken. 
https://github.com/OpenAPITools/openapi-generator/issues/12590 describes the problem we are having.

**Comment by aeneasr** [comment]
Does 6.2.1 also have this problem?

**Comment by jonas-jonas** [comment]
> Does 6.2.1 also have this problem?

For some reason, that has even more errors (`35 error in 110.86 second`) 

Not sure what's going on with the generators there. Apparently, [they are planning on releasing a completely reworked python generator soon, but no ETA yet.](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.2.0)

The same errors are present on 5.4.0 btw. I'll investigate a bit more tomorrow.

**Comment by aeneasr** [comment]
ok, maybe we can then work around this by fixing NullBool somehow

**Comment by aeneasr** [comment]
in 6.2.1 the experimental one is the default one, which is why this is probably failing with so many errors. try using `python-prior` generator with 6.2.1 - that is the original generator. maybe it has the problem fixed

**Comment by jonas-jonas** [comment]
That has the same 7 errors.

```
test/test_login_request.py:16: in <module>
    from ory_client.model.o_auth2_client import OAuth2Client
E     File "/project/clients/client/python/ory_client/model/o_auth2_client.py", line 38
E       globals()['from ory_client.model.null_duration import NullDuration'] = from ory_client.model.null_duration import NullDuration
E                                                                                 ^
E   SyntaxError: invalid syntax
```

It seems, that the generator, for some reason, does not remove the `ory_client.model.null_duration import` from `NullDuration`.

**Comment by jonas-jonas** [comment]
I think I figured out what the issue is, so I am documenting my findings here:

The client API spec contains two models called `OAuth2Client` (one capitalized and one not):
- `oAuth2Client` comes from the **Hydra** spec and is generated directly from the Go comments. See [v0.3.0.json#L2808](https://github.com/ory/sdk/blob/master/spec/client/v0.3.0.json#L2808)
- `OAuth2Client` comes from the **Kratos** spec and is generated by using `hydra-client-go`s OAuth2Client, which does not have any swagger annotations, but it's referred to by a model it is generated from the generated client code (generation-ception so to speak). See [v0.3.0.json#L242](https://github.com/ory/sdk/blob/master/spec/client/v0.3.0.json#L242)

I hope the fix is to use Open API patches to turn the "uppercase" one into `kratosOAuth2Client` in the Kratos repository so that they don't clash anymore. See https://github.com/ory/kratos/pull/2902

**Comment by jonas-jonas** [comment]
This is now fixed in the network repository, but we need an updated spec (presumably a  `v0.3.1` for this to be available in this repository.

**Comment by aeneasr** [comment]
v1.0.0 released fine - closing
