### ISSUE TITLE
kratos-client (typescript): Deprecated axios dependency => Severe Vulnerability Issues with current npm package

### ISSUE THREAD

**Issue by TMInnovations** [ory/sdk#57]
Please release an updated npm package that is not depending on a deprecated axios version.

(Almost) min. repo with angular installed: https://github.com/TMInnovations/kratos-client-vulnerabilities . Simply try to run `npm install --save @ory/kratos-client` and see the `2 high severity vulnerabilities`. 

The info block mentions `npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1.`.

Thank you and 
all the best!
Thomas

**Comment by aeneasr** [comment]
Hello, thank you for the report - however, this needs to be fixed in the upstream generator. The file is https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/package.mustache#L21

As you can see, it is already solved on master. However, it is still pending release: https://github.com/OpenAPITools/openapi-generator/blob/v5.0.0/modules/openapi-generator/src/main/resources/typescript-axios/package.mustache#L21

Once the release is out we can generate clients with the new axios version.

**Comment by PatrLind** [comment]
Seems like it is patched in >=0.21.1     
Perhaps you can update your dependencies?

**Comment by aeneasr** [comment]
Please read my comment: https://github.com/ory/sdk/issues/57#issuecomment-771687503

**Comment by aeneasr** [comment]
Looks like 5.0.1 is out: https://github.com/OpenAPITools/openapi-generator/releases

**Comment by philkuz** [comment]
I just installed `@ory-kratos-client-0.5.5-alpha.4` (latest release) and the vulnerable axios dependency is still around. Is it possible that something was messed up during the process and the dependency wasn't updated?

For anyone in the same position: I haven't had any issues forcing axios to the latest version by adding 
```json
  "resolutions": {
    "axios": "^0.21.1"
  }
``` 
to my package.json. YMMV

**Comment by aeneasr** [comment]
Hm looks like 5.1.0 is now out too, so maybe we switch to that. Hopefully that will finally resolve this...

**Comment by msanguineti** [comment]
> Hm looks like 5.1.0 is now out too, so maybe we switch to that. Hopefully that will finally resolve this...

Hello @aeneasr, hydra v1.10 is out but still this client problem persists? Any news on the update?
