### ISSUE TITLE
PHP deserialise problem for \Ory\Kratos\Client\Model\UiNode

### ISSUE THREAD

**Issue by splaunov** [ory/sdk#92]
**Describe the bug**

Getting error when calling initializeSelfServiceLoginFlowWithoutBrowser()

**To Reproduce**

        $configuration = new Configuration();
        $configuration->setHost("http://kratos:4433");
        $kratosApi = new V0alpha1Api(null, $configuration);
        $loginFlow = $kratosApi->initializeSelfServiceLoginFlowWithoutBrowser();

produces this error:

array:7 [
  "message" => "settype(): Invalid type"
  "class" => "ErrorException"
  "localized_message" => null
  "code" => null
  "errors" => array:79 [
    0 => array:4 [
      "function" => "handleError"
      "class" => "Illuminate\Foundation\Bootstrap\HandleExceptions"
      "type" => "->"
      "args" => array:5 [
        0 => 2
        1 => "settype(): Invalid type"
        2 => "/home/default/app/vendor/ory/kratos-client-php/lib/ObjectSerializer.php"
        3 => 335
        4 => array:3 [
          "data" => ""
          "class" => "mixed"
          "httpHeaders" => null
        ]
      ]
    ]
    1 => array:4 [
      "file" => "/home/default/app/vendor/ory/kratos-client-php/lib/ObjectSerializer.php"
      "line" => 335
      "function" => "settype"
      "args" => array:2 [
        0 => ""
        1 => "mixed"
      ]
    ]
    2 => array:6 [
      "file" => "/home/default/app/vendor/ory/kratos-client-php/lib/ObjectSerializer.php"
      "line" => 385
      "function" => "deserialize"
      "class" => "Ory\Kratos\Client\ObjectSerializer"
      "type" => "::"
      "args" => array:3 [
        0 => ""
        1 => "mixed"
        2 => null
      ]
    ]
    3 => array:6 [
      "file" => "/home/default/app/vendor/ory/kratos-client-php/lib/ObjectSerializer.php"
      "line" => 385
      "function" => "deserialize"
      "class" => "Ory\Kratos\Client\ObjectSerializer"
      "type" => "::"
      "args" => array:3 [
        0 => array:5 [
          "name" => "csrf_token"
          "type" => "hidden"
          "value" => ""
          "required" => true
          "disabled" => false
        ]
        1 => "\Ory\Kratos\Client\Model\UiNodeAttributes"
        2 => null
      ]
    ]
    4 => array:6 [
      "file" => "/home/default/app/vendor/ory/kratos-client-php/lib/ObjectSerializer.php"
      "line" => 286
      "function" => "deserialize"
      "class" => "Ory\Kratos\Client\ObjectSerializer"
      "type" => "::"
      "args" => array:3 [
        0 => array:5 [
          "type" => "input"
          "group" => "default"
          "attributes" => array:5 [
            "name" => "csrf_token"
            "type" => "hidden"
            "value" => ""
            "required" => true
            "disabled" => false
          ]
          "messages" => []
          "meta" => []
        ]
        1 => "\Ory\Kratos\Client\Model\UiNode"
        2 => null
      ]
    ]

**Expected behavior**

Should return deserialized login flow object.

**Environment**

- Version: v0.7
- Environment: MacOs, Docker, ...

**Additional context**

The problem is with the "value" attribute since it doesn't have the type set in the openapi spec.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!
